sonar.organization=romain-loutrel
sonar.projectKey=rloutrel_gnome-extension-nvme-monitor

sonar.projectName=gnome-extension-nvme-monitor

# No exclusions by default; narrow only if noise appears.
sonar.sources=.
sonar.tests=nvme-monitor@rloutrel.github.com/test
sonar.test.inclusions=**/*.test.js
sonar.coverage.exclusions=**/test/**
sonar.javascript.lcov.reportPaths=lcov.info
