#!/bin/bash
#
# setup-polkit.sh — Installation of the polkit + wrapper stack for the
# NVMe SMART GNOME Shell extension.
#
# Run once as root (via pkexec from the extension, or via sudo for testing).
#
# This script:
#   1. Detects the nvme binary path (portable across Fedora/Ubuntu/Debian).
#   2. Generates the wrapper /usr/local/bin/nvme-smart-log-json with the
#      resolved path hardcoded (no `which` at runtime → no PATH injection).
#   3. Creates the nvme-smart system group and adds the invoking user.
#   4. Deploys the .policy action for pkexec.
#   5. Deploys the polkit rule granting the action without password.
#   6. Installs the uninstall script + its own polkit action + rule.
#
# Target machine : any Linux with polkit, nvme-cli, GNOME Shell.
# Conforms to the freedesktop/ GNOME polkit philosophy.

set -euo pipefail

# ---------------------------------------------------------------------------
# Paths and identifiers (single source of truth)
# ---------------------------------------------------------------------------
WRAPPER_PATH="/usr/local/bin/nvme-smart-log-json"
UNINSTALL_PATH="/usr/local/bin/nvme-smart-uninstall.sh"
POLICY_DIR="/usr/share/polkit-1/actions"
RULES_DIR="/etc/polkit-1/rules.d"

ACTION_ID="org.freedesktop.policykit.pkexec.run-nvme"
UNINSTALL_ACTION_ID="org.freedesktop.policykit.pkexec.run-nvme-uninstall"

POLICY_FILE="org.freedesktop.policykit.pkexec.nvme.policy"
UNINSTALL_POLICY_FILE="org.freedesktop.policykit.pkexec.nvme-uninstall.policy"

RULE_FILE="10-nvme-smart-log.rules"
UNINSTALL_RULE_FILE="10-nvme-smart-uninstall.rules"

GROUP_NAME="nvme-smart"

# ---------------------------------------------------------------------------
# 0. Preflight checks
# ---------------------------------------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: this script must be run as root (use sudo or pkexec)." >&2
    exit 1
fi

# Identify the real user who invoked this (SUDO_USER for sudo, PKEXEC_UID for pkexec)
REAL_USER="${SUDO_USER:-}"
if [ -z "$REAL_USER" ] && [ -n "${PKEXEC_UID:-}" ]; then
    REAL_USER="$(getent passwd "$PKEXEC_UID" | cut -d: -f1)"
fi
if [ -z "$REAL_USER" ]; then
    echo "Error: could not determine the invoking user (SUDO_USER/PKEXEC_UID)." >&2
    exit 1
fi

echo "==> Installing NVMe SMART polkit stack for user: $REAL_USER"

# ---------------------------------------------------------------------------
# 1. Detect nvme binary (portable across distributions)
# ---------------------------------------------------------------------------
echo "==> Detecting nvme binary..."

if ! command -v nvme >/dev/null 2>&1; then
    echo "Error: nvme binary not found. Install the 'nvme-cli' package first." >&2
    echo "  Fedora: sudo dnf install nvme-cli" >&2
    echo "  Ubuntu: sudo apt install nvme-cli" >&2
    exit 1
fi

NVME_BIN="$(command -v nvme)"

# Resolve any symlink to the real binary (e.g. /usr/sbin → /usr/bin on Fedora)
NVME_BIN="$(readlink -f "$NVME_BIN")"

# Sanity check: refuse if the resolved path is not in a standard system directory
case "$NVME_BIN" in
    /usr/bin/nvme|/usr/sbin/nvme|/bin/nvme|/sbin/nvme)
        echo "    Found: $NVME_BIN"
        ;;
    *)
        echo "Error: nvme found at unusual path: $NVME_BIN" >&2
        echo "  Expected one of: /usr/bin/nvme, /usr/sbin/nvme, /bin/nvme, /sbin/nvme" >&2
        exit 1
        ;;
esac

# ---------------------------------------------------------------------------
# 2. Create the nvme-smart group and add the user
# ---------------------------------------------------------------------------
echo "==> Creating group $GROUP_NAME (if needed)..."

if ! getent group "$GROUP_NAME" >/dev/null 2>&1; then
    groupadd -r "$GROUP_NAME"
    echo "    Group created."
else
    echo "    Group already exists."
fi

echo "==> Adding user $REAL_USER to group $GROUP_NAME..."
if id -nG "$REAL_USER" | tr ' ' '\n' | grep -qx "$GROUP_NAME"; then
    echo "    User already in group."
else
    usermod -aG "$GROUP_NAME" "$REAL_USER"
    echo "    User added. A new login session is needed for this to take effect."
fi

# ---------------------------------------------------------------------------
# 3. Generate and install the wrapper script
# ---------------------------------------------------------------------------
echo "==> Installing wrapper: $WRAPPER_PATH"

cat > "$WRAPPER_PATH" <<EOF
#!/bin/bash
# Generated by setup-polkit.sh — do not edit by hand.
# Restricts nvme-cli to \`smart-log -o json\` on /dev/nvme* devices only.
# Polkit action: $ACTION_ID

set -euo pipefail

case "\${1:-}" in
  /dev/nvme*)
    exec $NVME_BIN smart-log -o json "\$1"
    ;;
  *)
    echo "nvme-smart-log-json: invalid or missing device argument (expected /dev/nvme*)" >&2
    exit 1
    ;;
esac
EOF

chown root:root "$WRAPPER_PATH"
chmod 0755 "$WRAPPER_PATH"

echo "    Wrapper installed (nvme path hardcoded: $NVME_BIN)."

# ---------------------------------------------------------------------------
# 4. Install the .policy action for the wrapper
# ---------------------------------------------------------------------------
echo "==> Installing polkit action: $POLICY_DIR/$POLICY_FILE"

cat > "$POLICY_DIR/$POLICY_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">

<policyconfig>

  <action id="$ACTION_ID">
    <description>Read NVMe SMART health logs (JSON)</description>
    <message>Authentication is required to read NVMe SMART information</message>

    <defaults>
      <allow_any>no</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>auth_admin</allow_active>
    </defaults>

    <annotate key="org.freedesktop.policykit.exec.path">$WRAPPER_PATH</annotate>
  </action>

</policyconfig>
EOF

chown root:root "$POLICY_DIR/$POLICY_FILE"
chmod 0644 "$POLICY_DIR/$POLICY_FILE"

echo "    Policy installed."

# ---------------------------------------------------------------------------
# 5. Install the polkit rule for the wrapper (no-password grant)
# ---------------------------------------------------------------------------
echo "==> Installing polkit rule: $RULES_DIR/$RULE_FILE"

cat > "$RULES_DIR/$RULE_FILE" <<'EOF'
// Generated by setup-polkit.sh — grants nvme-smart group members
// the right to run the SMART log wrapper via pkexec without password.
// Scope: local + active session only.

polkit.addRule(function (action, subject) {
    if (action.id === "org.freedesktop.policykit.pkexec.run-nvme" &&
        subject.isInGroup("nvme-smart") &&
        subject.active === true &&
        subject.local === true) {
        return polkit.Result.YES;
    }
});
EOF

chown root:root "$RULES_DIR/$RULE_FILE"
chmod 0644 "$RULES_DIR/$RULE_FILE"

echo "    Rule installed."

# ---------------------------------------------------------------------------
# 6. Install the uninstall script
# ---------------------------------------------------------------------------
echo "==> Installing uninstall script: $UNINSTALL_PATH"

cat > "$UNINSTALL_PATH" <<'UNINSTALL_EOF'
#!/bin/bash
# Generated by setup-polkit.sh — removes the NVMe SMART polkit stack.
# Run as root (via pkexec from the extension, or via sudo).
# This script deletes itself as its last action.

set -euo pipefail

WRAPPER_PATH="/usr/local/bin/nvme-smart-log-json"
UNINSTALL_PATH="/usr/local/bin/nvme-smart-uninstall.sh"
POLICY_DIR="/usr/share/polkit-1/actions"
RULES_DIR="/etc/polkit-1/rules.d"

POLICY_FILE="org.freedesktop.policykit.pkexec.nvme.policy"
UNINSTALL_POLICY_FILE="org.freedesktop.policykit.pkexec.nvme-uninstall.policy"
RULE_FILE="10-nvme-smart-log.rules"
UNINSTALL_RULE_FILE="10-nvme-smart-uninstall.rules"
GROUP_NAME="nvme-smart"

echo "==> Removing NVMe SMART polkit stack..."

# Remove wrapper
rm -f "$WRAPPER_PATH" && echo "    Removed: $WRAPPER_PATH"

# Remove policy files
rm -f "$POLICY_DIR/$POLICY_FILE" && echo "    Removed: $POLICY_DIR/$POLICY_FILE"
rm -f "$POLICY_DIR/$UNINSTALL_POLICY_FILE" && echo "    Removed: $POLICY_DIR/$UNINSTALL_POLICY_FILE"

# Remove rule files
rm -f "$RULES_DIR/$RULE_FILE" && echo "    Removed: $RULES_DIR/$RULE_FILE"

# Remove the uninstall rule last (but before self-deletion), so pkexec
# can still authorize THIS script during its own execution.
rm -f "$RULES_DIR/$UNINSTALL_RULE_FILE" && echo "    Removed: $RULES_DIR/$UNINSTALL_RULE_FILE"

# Remove the group (safe: at this point the only member was the user who
# installed, and the group grants nothing else).
if getent group "$GROUP_NAME" >/dev/null 2>&1; then
    groupdel "$GROUP_NAME" && echo "    Removed group: $GROUP_NAME"
fi

echo "==> Uninstall complete."

# Self-delete as the very last action.
rm -- "$0"
UNINSTALL_EOF

chown root:root "$UNINSTALL_PATH"
chmod 0755 "$UNINSTALL_PATH"

echo "    Uninstall script installed."

# ---------------------------------------------------------------------------
# 7. Install the polkit action for the uninstall script
# ---------------------------------------------------------------------------
echo "==> Installing uninstall polkit action: $POLICY_DIR/$UNINSTALL_POLICY_FILE"

cat > "$POLICY_DIR/$UNINSTALL_POLICY_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">

<policyconfig>

  <action id="$UNINSTALL_ACTION_ID">
    <description>Uninstall the NVMe SMART polkit stack</description>
    <message>Authentication is required to uninstall the NVMe SMART monitoring components</message>

    <defaults>
      <allow_any>no</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>auth_admin</allow_active>
    </defaults>

    <annotate key="org.freedesktop.policykit.exec.path">$UNINSTALL_PATH</annotate>
  </action>

</policyconfig>
EOF

chown root:root "$POLICY_DIR/$UNINSTALL_POLICY_FILE"
chmod 0644 "$POLICY_DIR/$UNINSTALL_POLICY_FILE"

echo "    Uninstall policy installed."

# ---------------------------------------------------------------------------
# 8. Install the polkit rule for the uninstall script (no-password grant)
# ---------------------------------------------------------------------------
echo "==> Installing uninstall polkit rule: $RULES_DIR/$UNINSTALL_RULE_FILE"

cat > "$RULES_DIR/$UNINSTALL_RULE_FILE" <<'EOF'
// Generated by setup-polkit.sh — grants nvme-smart group members
// the right to run the uninstall script via pkexec without password.
// Scope: local + active session only.

polkit.addRule(function (action, subject) {
    if (action.id === "org.freedesktop.policykit.pkexec.run-nvme-uninstall" &&
        subject.isInGroup("nvme-smart") &&
        subject.active === true &&
        subject.local === true) {
        return polkit.Result.YES;
    }
});
EOF

chown root:root "$RULES_DIR/$UNINSTALL_RULE_FILE"
chmod 0644 "$RULES_DIR/$UNINSTALL_RULE_FILE"

echo "    Uninstall rule installed."

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
echo "==> Installation complete."
echo ""
echo "    Wrapper:   $WRAPPER_PATH"
echo "    Policy:    $POLICY_DIR/$POLICY_FILE"
echo "    Rule:      $RULES_DIR/$RULE_FILE"
echo "    Uninstall: $UNINSTALL_PATH"
echo ""
echo "    IMPORTANT: log out and back in (or reboot) so that your group"
echo "    membership in '$GROUP_NAME' is effective in your GNOME session."
echo ""
echo "    Then test with:"
echo "      pkexec $WRAPPER_PATH /dev/nvme0n1"
echo "    (should run without a password prompt)"