name: shexli

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  shexli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Analyze extension source with shexli
        uses: 3v1n0/shexli-ci@c31b5dc22ae7acd684e5ec9ee6728f39ac2e1eac # v1
        with:
          path: nvme-monitor@rloutrel.github.com
